### ISSUE TITLE
Multiple same amino acids with differential modifications

### ISSUE THREAD

**Issue by heejongkim** [OrgMassSpec/OrgMassSpecR#3]
Hello,

Thanks for sharing the great package.
As I'm utilizing the FragmentPeptide function to generate the theoretical fragmentation pattern for plotting PeptideSpectrum, I encountered the issue that it seems there's no way to handle multiple same amino acids (e.g. **K**ABCD**K**EFG**K**) with different mods (e.g. ubi on K, me on K, and ac on K) at the same time since the custom list can take single amino acid with single "custom" mass.
If you have an idea for this, it would be awesome!

Thanks,
hee jong

**Comment by OrgMassSpec** [comment]
Hi,

FragmentPeptide can take multiple custom amino acids as follows:

```
k.mass <- 134.1151
m.mass <- 147.0354
FragmentPeptide("NDmELWk", custom = list(code = c("m", "k"), mass = c(m.mass, k.mass)))
```
In your case, try selecting three lower case letters to define the three K modifications:
```
FragmentPeptide("aABCDbEFGc", custom = list(code = c("a", "b", "c"), mass = c(a.mass, b.mass, c.mass)))
```

I think selecting 3 different letters for the three modifications is the only way. 

Best,
Nate

**Comment by heejongkim** [comment]
Thank you for the fast response.
I guess I need a little bit of parsing before and after to get a correct peptide sequence in the end.

Thanks!
hee jong
