### ISSUE TITLE
FragmentPeptide Mass tolerance

### ISSUE THREAD

**Issue by heejongkim** [OrgMassSpec/OrgMassSpecR#5]
Hi,

One thing that I noticed about the FragmentPeptide function is that there's no Da/ppm mass tolerance for different types of the mass analyzer (Orbitrap, ion trap, etc). It seems like all ions are rounded by digits=3. I'm not quite sure that it will be sufficient for low-resolution cases, such as ion trap.
Is there a way to control from a user-side?

Thanks,
hee jong

**Comment by OrgMassSpec** [comment]
Hi - Yes, all m/z values are rounded with digits = 3 and there is no function argument to control this. You may modify the source code to change the rounding behavior. Best,
Nate
