### ISSUE TITLE
ConvertConcentration does opposite of expected

### ISSUE THREAD

**Issue by A-W-Smith** [OrgMassSpec/OrgMassSpecR#8]
Hi, the function `ConvertConcentration` appears to go the opposite of how I would expect.

For example, `ConvertConcentration(10, "wet.to.lipid", 50)`, results in 20, but should it not equal 5? As the lipid weight should be less than the wet weight.

![image](https://user-images.githubusercontent.com/9109494/152543529-4b7f1afb-abc4-489c-9d97-20149d537974.png)

Taking the lipid percentage calculation from the above formula, if I wanted to convert from wet to lipid, it would be the following calculation:
`lipid <- wet * (percent.lipid / 100)`

However, when I check the source code, I see the opposite:
` lipid <- wet * (100 / percent.lipid)`

Wet to dry conversion also appear reversed to me, please could you clarify

Thanks

**Comment by OrgMassSpec** [comment]
Hi,

As an example, the equations used follow the document here: https://ofmpub.epa.gov/eims/eimscomm.getfile?p_download_id=527074

See Eqn. 10-5 for dry weight to wet weight and Eqn. 10-7 for lipid weight to wet weight. 

Concentrations on a lipid weight basis have higher values than on a wet weight basis. For example, see the following that reports the same data both ways (Tables 2 and 3): https://www.sciencedirect.com/science/article/pii/S0013935118304328. Lipid weight (g lipid) of a sample is a fraction of the sample's wet weight (g wet weight). So when converting from ng/g wet weight to ng/g lipid weight, the value of the concentration should increase.
